import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "../../../../lib/admin-auth";
import fs from "fs/promises";
import path from "path";

const dataFile = path.join(
  process.cwd(),
  "data",
  "content.json"
);

async function authorized() {
  return await isAdminAuthenticated();
}

async function readContent() {
  try {
    return JSON.parse(
      await fs.readFile(dataFile, "utf8")
    );
  } catch {
    return [];
  }
}

async function saveContent(items) {
  await fs.mkdir(path.dirname(dataFile), {
    recursive: true,
  });

  await fs.writeFile(
    dataFile,
    JSON.stringify(items, null, 2)
  );
}

export async function GET() {
  if (!(await authorized())) {
    return NextResponse.json(
      { success: false, error: "Unauthorized" },
      { status: 401 }
    );
  }

  return NextResponse.json({
    success: true,
    items: await readContent(),
  });
}

export async function PUT(request) {
  if (!(await authorized())) {
    return NextResponse.json(
      { success: false, error: "Unauthorized" },
      { status: 401 }
    );
  }

  try {
    const body = await request.json();

    if (!body.id) {
      return NextResponse.json(
        { success: false, error: "Content ID is required" },
        { status: 400 }
      );
    }

    const items = await readContent();

    const index = items.findIndex(
      (item) => item.id === body.id
    );

    if (index === -1) {
      return NextResponse.json(
        { success: false, error: "Content not found" },
        { status: 404 }
      );
    }

    items[index] = {
      ...items[index],

      title:
        body.title !== undefined
          ? String(body.title).trim()
          : items[index].title,

      description:
        body.description !== undefined
          ? String(body.description).trim()
          : items[index].description,

      thumbnailUrl:
        body.thumbnailUrl !== undefined
          ? String(body.thumbnailUrl).trim()
          : items[index].thumbnailUrl || "",

      published:
        typeof body.published === "boolean"
          ? body.published
          : items[index].published !== false,

      updatedAt: new Date().toISOString(),
    };

    await saveContent(items);

    return NextResponse.json({
      success: true,
      item: items[index],
    });
  } catch (error) {
    console.error("CONTENT UPDATE ERROR:", error);

    return NextResponse.json(
      {
        success: false,
        error: "Update failed",
      },
      { status: 500 }
    );
  }
}

export async function DELETE(request) {
  if (!(await authorized())) {
    return NextResponse.json(
      { success: false, error: "Unauthorized" },
      { status: 401 }
    );
  }

  try {
    const body = await request.json();

    if (!body.id) {
      return NextResponse.json(
        { success: false, error: "Content ID is required" },
        { status: 400 }
      );
    }

    const items = await readContent();

    const item = items.find(
      (content) => content.id === body.id
    );

    if (!item) {
      return NextResponse.json(
        { success: false, error: "Content not found" },
        { status: 404 }
      );
    }

    /*
     * Remove the uploaded file.
     * Only paths generated by our upload system
     * under public/uploads are allowed.
     */
    if (item.downloadUrl?.startsWith("/uploads/")) {
      const relative = item.downloadUrl.replace(
        /^\/+/,
        ""
      );

      const uploadRoot = path.resolve(
        process.cwd(),
        "public",
        "uploads"
      );

      const filePath = path.resolve(
        process.cwd(),
        "public",
        relative
      );

      if (
        filePath === uploadRoot ||
        !filePath.startsWith(uploadRoot + path.sep)
      ) {
        return NextResponse.json(
          {
            success: false,
            error: "Unsafe file path",
          },
          { status: 400 }
        );
      }

      try {
        await fs.unlink(filePath);
      } catch (error) {
        if (error.code !== "ENOENT") {
          console.error(
            "PHYSICAL FILE DELETE ERROR:",
            error
          );
        }
      }
    }

    const updated = items.filter(
      (content) => content.id !== body.id
    );

    await saveContent(updated);

    return NextResponse.json({
      success: true,
      message: "Content and uploaded file deleted",
      items: updated,
    });
  } catch (error) {
    console.error("CONTENT DELETE ERROR:", error);

    return NextResponse.json(
      {
        success: false,
        error: "Delete failed",
      },
      { status: 500 }
    );
  }
}
